sudo: required

services:
  - docker

script:
  - export TRAVIS_DEBIAN_DISTRIBUTION=xenial; tools/docker-ubuntu.sh
  - ls -alrt
  - ls -alrt ..

branches:
  except:
    - /^debian\/\d/

before_deploy:
  - export DEB_FILES=$(ls *.deb)
  - echo "deploying $DEB_FILES to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: M9P/uji1XmpIJoURmhOpKA/xPneEABIMIRYt42nv+Pa3XVLTByiqhPQTNLNSoPwQTVAP/HU09u3QD07Qi1WLfYdg+AA7tlc+EAqFv7lStykybAhfyh/fXjIy/gw1YmIKT7HV9yv0yonsJ6u6ibSSANJbpUxXDxR0xvzPDDWTy9lLoLdnEmjhM3TxzIFon9HvzxWQ5Ko7f9WB2KjkM/5GmqrgSTMMnAArgIEHxNS3fUevLE7eYp3qOYR42Ccd6SLXqsZfcXY6OK9zojT3DgyIrXgt5CY4ci9cT09fg883ajIycTZFqEx9NBTs4c5tsAzLLikmPaUBcr+hw5IkcxTWyo4w6c3sWgTUhhTGVnY5Rq/c4Vd442aoomshTollldyT8OyUH57FMlfPmCPUEBF4aRkDrDk3F0pOQudQeW3cCg/Wz1W+3ah+m+GN5zGqLgWE5mtuVBBDhEyjJ/EDG1th+FkMOmpos0OocIYKSw/rxzHUeHcgPvLY22ig3k7KePsI06jY7Gnvn9XpsFcfkPbe9R/JUZhPge4VSii5fv8vdMDZaT8tO9IebfD51w3a/xmR40tGGFIYy674uqY1z61kPpIQKzrCbkA45Y6Qy94C5EicKEUf+f4ZW59gtGnaesD4vkceUuL+dCJFCgQMRpYHqSOcea7laCgcyhp5x2otK3A=
  file_glob: true
  file: "${DEB_FILES}"
  on:
    tags: true
